<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IcebergDetector</AssemblyName>
    <RootNamespace>IcebergDetector</RootNamespace>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.Indicators.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ATAS.DataFeedsCore">
      <HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.DataFeedsCore.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OFT.Drawing">
      <HintPath>C:\Program Files (x86)\ATAS Platform\OFT.Drawing.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
